const ImagesActionTypes = {
	SET_IMAGE: 'SET_IMAGE',
	SET_CURRENT_IMAGE: 'SET_CURRENT_IMAGE',
	INVOKE_IMAGE_EDITOR: 'INVOKE_IMAGE_EDITOR',
	INVOKE_IMAGE_PREVIEW: 'INVOKE_IMAGE_PREVIEW',
	SET_CURRENT_IDX: 'SET_CURRENT_IDX',
	
}

export default ImagesActionTypes;